import { StyleSheet } from "react-native";

/** Styles shared by transaction form + bulk modals (matches TransactionsScreen). */
export const txnEditorStyles = StyleSheet.create({
  backdrop: { flex: 1, backgroundColor: "rgba(0,0,0,0.35)" },
  txnModalKeyboardRoot: {
    flex: 1,
  },
  txnModalKeyboardInner: {
    flex: 1,
    justifyContent: "flex-end",
  },
  txnModalBackdropDim: {
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  txnModalScrollContent: {
    gap: 10,
    paddingBottom: 28,
  },
  sheet: {
    backgroundColor: "#FFFFFF",
    flex: 1,
    width: "100%",
    padding: 16,
  },
  sheetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sheetTitle: {
    color: "#0B0B0B",
    fontSize: 16,
    fontFamily: "Poppins_700Bold",
  },
  closeBtn: {
    borderWidth: 1,
    borderColor: "#0B0B0B",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  closeBtnPressed: { backgroundColor: "#F5F5F5" },
  closeBtnText: {
    color: "#0B0B0B",
    fontFamily: "Poppins_600SemiBold",
    fontSize: 12,
  },
  label: { color: "#0B0B0B", fontFamily: "Poppins_600SemiBold", fontSize: 12 },
  inputMultiline: {
    minHeight: 88,
    paddingTop: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: "#E7E7E7",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#0B0B0B",
    fontFamily: "Poppins_400Regular",
    fontSize: 13,
  },
  pickerBtn: {
    borderWidth: 1,
    borderColor: "#E7E7E7",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  pickerBtnPressed: { backgroundColor: "#F5F5F5" },
  pickerBtnText: {
    color: "#0B0B0B",
    fontFamily: "Poppins_600SemiBold",
    fontSize: 13,
  },
  moneyRow: { flexDirection: "row", gap: 10 },
  typePill: {
    borderWidth: 1,
    borderColor: "#E7E7E7",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 10,
    backgroundColor: "#FFFFFF",
  },
  typePillPressed: { backgroundColor: "#F5F5F5" },
  typePillCreditActive: { borderColor: "#0FA958", backgroundColor: "#0FA958" },
  typePillDebitActive: { borderColor: "#E53935", backgroundColor: "#E53935" },
  typePillText: {
    color: "#0B0B0B",
    fontFamily: "Poppins_600SemiBold",
    fontSize: 12,
  },
  typePillTextActive: { color: "#FFFFFF" },
  saveBtn: {
    marginTop: 6,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0B0B0B",
  },
  saveBtnPressed: { opacity: 0.88 },
  saveBtnText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontFamily: "Poppins_700Bold",
  },
  deleteBtn: {
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E53935",
    marginTop: 6,
  },
  deleteBtnPressed: { opacity: 0.88 },
  deleteBtnRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  deleteBtnText: {
    color: "#FFFFFF",
    fontFamily: "Poppins_700Bold",
    fontSize: 13,
  },
  pickerSheet: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E7E7E7",
    padding: 16,
    margin: 16,
    maxHeight: "75%",
  },
  /** Full-screen picker (account / person / category) in TransactionFormModal. */
  pickerModalRoot: { flex: 1, backgroundColor: "#FFFFFF" },
  pickerSheetFull: { flex: 1, width: "100%" },
  pickerSheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E7E7E7",
  },
  pickerTitleInHeader: {
    flex: 1,
    color: "#0B0B0B",
    fontFamily: "Poppins_700Bold",
    fontSize: 16,
  },
  pickerListScroll: { flex: 1 },
  pickerListContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 32,
    gap: 8,
    flexGrow: 1,
  },
  pickerSearchInFull: {
    marginHorizontal: 16,
    marginBottom: 10,
  },
  pickerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  pickerTitle: {
    color: "#0B0B0B",
    fontFamily: "Poppins_700Bold",
    fontSize: 14,
  },
  pickerSearchInput: {
    borderWidth: 1,
    borderColor: "#E7E7E7",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#FFFFFF",
    fontFamily: "Poppins_400Regular",
    fontSize: 13,
    color: "#0B0B0B",
    marginBottom: 10,
  },
  pickerRow: {
    borderWidth: 1,
    borderColor: "#E7E7E7",
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  pickerCreateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  /** Person list in TransactionFormModal: flex-wrap chips instead of one column. */
  pickerChipGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingTop: 2,
  },
  pickerChip: {
    borderWidth: 1,
    borderColor: "#E7E7E7",
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: "#FAFAFA",
  },
  pickerChipPressed: { backgroundColor: "#F5F5F5" },
  pickerChipText: {
    color: "#0B0B0B",
    fontFamily: "Poppins_600SemiBold",
    fontSize: 13,
  },
  pickerRowPressed: { backgroundColor: "#F5F5F5" },
  pickerRowText: {
    color: "#0B0B0B",
    fontFamily: "Poppins_600SemiBold",
    fontSize: 13,
  },
  sidebarTxnTypeWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  sidebarTxnTypePill: {
    borderWidth: 1,
    borderColor: "#E7E7E7",
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: "#FFFFFF",
  },
  sidebarTypePillActiveNeutral: {
    borderColor: "#0B0B0B",
    backgroundColor: "#0B0B0B",
  },
  sidebarTxnTypePillText: {
    color: "#0B0B0B",
    fontFamily: "Poppins_600SemiBold",
    fontSize: 12,
  },
  bulkChipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  bulkChipBtn: {
    borderWidth: 1,
    borderColor: "#E7E7E7",
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: "#FFFFFF",
  },
  bulkChipText: {
    color: "#0B0B0B",
    fontFamily: "Poppins_600SemiBold",
    fontSize: 12,
  },
  pickerRowActive: { borderColor: "#0B0B0B", backgroundColor: "#F5F5F5" },
  secondaryResetBtn: {
    borderWidth: 1,
    borderColor: "#0B0B0B",
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  secondaryResetBtnPressed: { backgroundColor: "#F5F5F5" },
  secondaryResetText: {
    color: "#0B0B0B",
  },
  bulkActionsRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#E7E7E7",
  },
  bulkBar: {
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  bulkBarText: {
    color: "#0B0B0B",
    fontFamily: "Poppins_600SemiBold",
    fontSize: 12,
  },
  bulkActionBtn: {
    borderWidth: 1,
    borderColor: "#E7E7E7",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: "#FFFFFF",
  },
  bulkActionBtnPressed: { backgroundColor: "#F5F5F5" },
  bulkActionBtnText: {
    color: "#0B0B0B",
    fontFamily: "Poppins_600SemiBold",
    fontSize: 12,
  },
  bulkDangerBtn: {
    borderWidth: 1,
    borderColor: "#B42318",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: "#FFF5F5",
  },
  bulkDangerBtnPressed: { backgroundColor: "#FEEAEA" },
  bulkDangerBtnText: {
    color: "#B42318",
    fontFamily: "Poppins_600SemiBold",
    fontSize: 12,
  },
});
