# Generated by Django 5.2.3 on 2026-03-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_category_alter_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='txn_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('loan_given', 'Loan Given'), ('loan_taken', 'Loan Taken'), ('repayment_in', 'Repayment In'), ('repayment_out', 'Repayment Out')], default='expense', max_length=20),
        ),
    ]
