# Generated by Django 5.2.3 on 2026-03-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='loan',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
