# Generated by Django 5.2.3 on 2026-03-26 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_person_id'),
        ('transactions', '0006_remove_transaction_loan_delete_loan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('members', models.ManyToManyField(related_name='split_groups', to='people.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SplitGroupTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.splitgroup')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_groups', to='transactions.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['group'], name='transaction_group_i_887d2c_idx'), models.Index(fields=['transaction'], name='transaction_transac_14359f_idx')],
                'unique_together': {('group', 'transaction')},
            },
        ),
        migrations.CreateModel(
            name='SplitItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_items', to='transactions.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['transaction'], name='transaction_transac_e8fcdc_idx'), models.Index(fields=['person'], name='transaction_person__4c5b9b_idx')],
                'unique_together': {('transaction', 'person')},
            },
        ),
    ]
