# Generated by Django 5.2.3 on 2026-03-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_splitgroup_splitgrouptransaction_splititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionupload',
            name='processing_errors',
            field=models.TextField(blank=True, default=''),
        ),
    ]
