# Generated by Django 5.2.3 on 2026-03-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transactionupload_processing_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
