# Generated by Django 5.2.3 on 2026-04-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transaction_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
